apiVersion: v1.1
resources:
  - name: containerEnvExample
    type: declarativesystems/ContainerEnv
    configuration:
      sourceArtifactory: artifactory
  - name: gitPipelinesExampleContainerEnv
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/pipelines_example_containerenv
      branches:
        include: ^{{gitBranch}}$
      cancelPendingRunsOn:
        pullRequestUpdate: true
        newCommit: true

pipelines:
  - name: pipelinesExampleContainerEnv
    configuration:
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10
      runtime:
        type: image
        image:
          custom:
            name: declarativesystems.jfrog.io/docker-local/pipelines
            tag: 0.9.0
            registry: artifactory
            sourceRepository: docker-local
    steps:
      - name: buildAndPushContainerImage
        type: Bash
        configuration:
          integrations:
            - name: artifactory
          inputResources:
            - name: containerEnvExample
            - name: gitPipelinesExampleContainerEnv
        execution:
          onExecute:
            - cd ${res_gitPipelinesExampleContainerEnv_resourcePath}
            - make push
